# GENERATED by script/generate_icons.rb — do not edit by hand.
#
# Cache-busting token appended (?v=) to favicon / app-icon / splash URLs. It is
# a content hash of the icon masters, so it changes exactly when the art does —
# forcing browsers (and iOS, which caches the home-screen icon hard by URL) to
# refetch instead of serving a stale icon. A plain top-level constant so both
# the layout and the PWA manifest view (rendered outside ApplicationController)
# can read it.
ICON_VERSION = "a7be5489".freeze
