#!/usr/bin/env python3
"""
Subset BOTH Phosphor artifacts — the icon font and its CSS — to only the glyphs
üsgu actually uses.

Why: the full Phosphor.woff2 is ~147 KB (~1,500 glyphs) and the full phosphor.css
is ~78 KB (~1,500 class definitions), but the app renders only a couple dozen
icons. Shipping either in full on every cold start is wasteful — the CSS is on the
render-blocking bundle — so we ship a font subset + a matching CSS trim containing
exactly the used glyphs. Both derive from the same `used` set, so they cannot
drift: a removed/typo'd icon drops out of font AND CSS together.

This is the REGENERATE mechanism. Re-run it whenever you add or remove a `ph-…`
icon class anywhere in the app — it re-derives the used set from the source tree,
so there is no hand-maintained list:

    pip install --user fonttools brotli      # one-time prerequisite
    python3 script/subset_phosphor.py

Inputs (masters — NEVER edit/subset these; they hold the full vocabulary):
  - vendor/phosphor/Phosphor.woff2        full master font
  - vendor/phosphor/phosphor.css          full class -> codepoint map + base rules
  - every tracked source file             which `ph-…` classes are referenced

Outputs (build artifacts — committed, but regenerated by this script):
  - app/assets/fonts/Phosphor.woff2       subset font, referenced by the CSS
  - app/assets/stylesheets/phosphor.css   trimmed CSS, served on every page

A `ph-…` class whose glyph isn't in the subset renders as a blank box — but since
the trimmed CSS only emits used classes, adding an icon to the markup without
re-running this leaves the class undefined (no glyph at all), which is exactly the
signal to re-run. The script fails loudly if a used class has no codepoint.
"""
import re
import subprocess
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
CSS_MASTER = ROOT / "vendor/phosphor/phosphor.css"
MASTER = ROOT / "vendor/phosphor/Phosphor.woff2"
OUT = ROOT / "app/assets/fonts/Phosphor.woff2"
OUT_CSS = ROOT / "app/assets/stylesheets/phosphor.css"

# Exclude both the master map and our own trimmed output from the source scan:
# the master lists ALL ~1,500 classes (scanning it would mark every icon "used"
# and defeat subsetting), and the output only ever contains the already-used set.
CSS_MASTER_REL = "vendor/phosphor/phosphor.css"
OUT_CSS_REL = "app/assets/stylesheets/phosphor.css"
SCAN_SKIP = {CSS_MASTER_REL, OUT_CSS_REL}
TOKEN = re.compile(r"ph-[a-z0-9]+(?:-[a-z0-9]+)*")
# .ph.ph-bell:before { content: "\e0ce"; }  (selector and content may span lines)
DEF = re.compile(r"\.ph\.(ph-[a-z0-9-]+):before\s*\{\s*content:\s*\"\\([0-9a-fA-F]+)\"")


def main():
    if not MASTER.exists():
        sys.exit(f"missing master font: {MASTER} (the full, un-subset Phosphor.woff2)")
    if not CSS_MASTER.exists():
        sys.exit(f"missing master CSS: {CSS_MASTER} (the full, un-trimmed phosphor.css)")

    # 1. class -> codepoint, parsed straight from the master CSS. Everything before
    #    the first glyph def (the @font-face + base `.ph` rule) is the header we
    #    carry verbatim into the trimmed output.
    master_css = CSS_MASTER.read_text()
    first = DEF.search(master_css)
    if not first:
        sys.exit(f"parsed zero glyph definitions from {CSS_MASTER_REL} — did the format change?")
    header = master_css[: first.start()].rstrip() + "\n"
    defs = {m.group(1): int(m.group(2), 16) for m in DEF.finditer(master_css)}

    # 2. which ph- classes the app references (every tracked file except the two
    #    phosphor CSS files — see SCAN_SKIP). Intersecting with `defs` keeps only
    #    real icon classes, so stray matches like "ph-5" or genre slugs containing
    #    "ph-" fall away on their own.
    files = subprocess.check_output(["git", "ls-files"], cwd=ROOT).decode().splitlines()
    used = set()
    for rel in files:
        if rel in SCAN_SKIP:
            continue
        try:
            text = (ROOT / rel).read_text(errors="ignore")
        except (OSError, UnicodeDecodeError):
            continue
        used.update(tok for tok in TOKEN.findall(text) if tok in defs)

    if not used:
        sys.exit("found no used `ph-…` icon classes — refusing to build an empty font")

    codepoints = sorted(defs[c] for c in used)
    unicodes = ",".join(f"U+{cp:04X}" for cp in codepoints)

    print(f"used icons: {len(used)}")
    for cls in sorted(used):
        print(f"  {cls:32} U+{defs[cls]:04X}")

    before = MASTER.stat().st_size

    # 3. subset. Access is by codepoint (CSS `content`), so we drop layout
    #    features (ligatures) and hinting — none of it is reachable.
    subprocess.check_call([
        sys.executable, "-m", "fontTools.subset", str(MASTER),
        f"--unicodes={unicodes}",
        "--layout-features=",
        "--no-hinting",
        "--desubroutinize",
        "--flavor=woff2",
        f"--output-file={OUT}",
    ])

    # 4. verify every requested codepoint actually survived into the subset.
    from fontTools.ttLib import TTFont
    cmap = set()
    with TTFont(OUT) as font:
        for table in font["cmap"].tables:
            cmap.update(table.cmap.keys())
    missing = [c for c in codepoints if c not in cmap]
    if missing:
        sys.exit("subset is MISSING codepoints: " + ", ".join(f"U+{c:04X}" for c in missing))

    after = OUT.stat().st_size
    print(f"\nwrote {OUT.relative_to(ROOT)}")
    print(f"{before:,} -> {after:,} bytes ({100 * after / before:.1f}% of original)")

    # 5. emit the matching trimmed CSS: header verbatim + only the used glyph
    #    defs, rebuilt canonically from the same map the font subset used.
    css_before = len(master_css.encode())
    body = "\n".join(
        f'.ph.{cls}:before {{\n  content: "\\{defs[cls]:x}";\n}}'
        for cls in sorted(used)
    )
    OUT_CSS.write_text(header + "\n" + body + "\n")
    css_after = OUT_CSS.stat().st_size
    print(f"wrote {OUT_CSS.relative_to(ROOT)}")
    print(f"{css_before:,} -> {css_after:,} bytes ({100 * css_after / css_before:.1f}% of original)")


if __name__ == "__main__":
    main()
